version: '3'
services:
  aws:
    image: rammohan478/aws
    ports:
      - "80:80"
    deploy:
      replicas: 3

  devops:
    image: rammohan478/devops 
    ports:
      - "81:80"
    deploy:
      replicas: 3

  azure:
    image: rammohan478/azure
    ports:
      - "82:80"
    deploy:
      replicas: 3

  datascience:
    image: rammohan478/datascience
    ports:
      - "83:80"
    deploy:
      replicas: 3
